apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: ecommerce
type: Opaque
data:
  # Valeurs encodées en base64 (ex: password -> cGFzc3dvcmQ=)
  DB_PASSWORD: cGFzc3dvcmQ=
  # JWT secret key (base64 encoded: "your-secret-key")
  JWT_SECRET_KEY: eW91ci1zZWNyZXQta2V5
